# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Talk_pb2 as Talk__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Talk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeakxServiceStub(object):
    """service to expose a remote method
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Talk = channel.unary_unary(
                '/Talk.SpeakxService/Talk',
                request_serializer=Talk__pb2.Greeting.SerializeToString,
                response_deserializer=Talk__pb2.ResponseGreeting.FromString,
                _registered_method=True)


class SpeakxServiceServicer(object):
    """service to expose a remote method
    """

    def Talk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Talk': grpc.unary_unary_rpc_method_handler(
                    servicer.Talk,
                    request_deserializer=Talk__pb2.Greeting.FromString,
                    response_serializer=Talk__pb2.ResponseGreeting.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Talk.SpeakxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Talk.SpeakxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeakxService(object):
    """service to expose a remote method
    """

    @staticmethod
    def Talk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Talk.SpeakxService/Talk',
            Talk__pb2.Greeting.SerializeToString,
            Talk__pb2.ResponseGreeting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
